language: php

sudo: false

cache:
  directories:
    - $HOME/.cache

before_cache:
  - sudo chown -R travis:travis $HOME/.cache

php:
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - bin/phpunit